### ISSUE TITLE
Argentine Spanish

### ISSUE THREAD

**Issue by Texaliuz** [xChillax/PZBetterMoodlesDescriptions#14]
Could you please add the translation into Argentinean Spanish?
[Moodles_AR.txt](https://github.com/user-attachments/files/17150149/Moodles_AR.txt)
the encoding is “ANSI” or “windows 1252”.

**Comment by xChillax** [comment]
The AR translation is already in place, I'm gonna assume that it just wasn't pushed to the workshop item itself.
